version: '3.7'

services:
  game-server:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "8900:8900"

  game-server-test:
    build:
      context: .
      target: test
